### ISSUE TITLE
提议：重新设计主题的切换与自定义机制

### ISSUE THREAD

**Issue by firede** [geist-org/react#353]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

#### 目前 `切换主题` 与 `自定义主题` 的机制存在歧义

直觉上，应该可以在 dark 类型的基础上修改 `palette.success` 颜色。但事实上，这样只能切换到内置主题。

```js
const myTheme = {
  type: "dark",
  palette: { success: "#50E3C2" },
}
<ZeitProvider theme={myTheme} />
```

文档中，切换主题的方法是只传入 `type`，这样无法与「基于内置 `type` 自定义主题」的意图兼容。

```js
<ZeitProvider theme={{ type: "dark" }} />
```

如果在不传入 `type: "dark"` 的情况下定制了深色主题，会出现组件中因对 `type` 的依赖造成的功能缺失，例如：

内置 dark 主题下 `Tooltip` / `Popover` 的箭头：
<img src="https://user-images.githubusercontent.com/157338/89098539-3369d200-d41b-11ea-8d61-905e63d0bccb.png" width="178" />

自定义深色主题 `Tooltip` / `Popover` 的箭头：
<img src="https://user-images.githubusercontent.com/157338/89098593-965b6900-d41b-11ea-8b01-154149819a1f.png" width="184" />

https://github.com/zeit-ui/react/blob/fa988dafbaf1967402f02b3e2e8e788f397b7e8e/components/tooltip/tooltip-icon.tsx#L17-L20

### Expected / Programme

`ZeitProvider` 的 `theme` 参数承载了 `切换主题` 与 `自定义主题` 两种意图，theme 机制也过于复杂，建议简化：

1. `type` 作为主题的外观类型（`light` / `dark`），不代指任何内置主题
2. `ZeitProvider` 传入的 `theme` 需要是完整主题（少些魔法，简化逻辑）
3. 默认主题导出为 `lightTheme`、`darkTheme`，直接引入使用

这样在使用默认主题时可以：

```js
import { darkTheme } from "@zeit-ui/react"

<ZeitProvider theme={darkTheme} />
```

自定义主题时可以：

```js
import { darkTheme } from "@zeit-ui/react"

// 基于现有主题
const myTheme = merge(darkTheme, {
  palette: { success: "#50E3C2" },
  font: { mono: "SF Mono" },
})

// 完整自定义主题（TypeScript 验证完整性）
const myTheme: ZeitUIThemes = {
  type: "dark",
  font: { /* ... */ },
  // ...
}


<ZeitProvider theme={myTheme} />
```

### Others (Optional)

PS: 官网定制化功能，在 dark 模式下是无效的。

**Comment by unix** [comment]
👍 很好的提议。这是一个 API 设计上的债务，组件库早期只能切换主题而没有考虑到自定义每个样式，现在看来 `Themes` 不能很好的在 **主题类型切换** 和 **自定义主题** 两者上同时工作。

当前的所有可用方案和工作方式：

  - 通过 `theme={}` 修改主题，遗憾的是，主题的类型接口是固定的，而且存在默认主题，会被默认主题覆盖。
  - 可以通过 `@zeit-ui/react/dist/styles/themes/` 引入 `default` / `dark` 的默认主题常量。
  - 所有的 `themes` 字段都是可选的。(因为会发生一次默认的合并)

原有 API 设计的初衷是尽可能地让用户少编写代码，最好能让用户不手动使用 `merge`，切换主题时不需要额外的声明式的代码，但也引入了 **修改主题** 与 **切换主题** 的边界模糊问题。作为解决方案，可以有以下几种设计方案：

  1. `themes={[]}` 接口只作为定义主题使用，此外增加 `themeType` 切换指定的主题。
  2. 不做 API 上的破坏性变更，但至少强制要求 `{ type: string }` 为必填项，以便于为自定义的内容分配主题。
  3. 导出所有的默认主题，并且强制要求每一项为必填项。但 `type` 仍旧会指定默认主题。
  4. 与 3 相同，但 `type` 只作为标识，每次都需要声明全新的主题对象。(与你提出的方案类似)

我认为你的方案 (4) 是一个不错的解决方式，但这会引起比较大的破坏性变更，以至于所有曾经使用 `theme.type` 切换主题的用户都需要被迫迁移。我想还需要保留原有 API 的工作方式，但提出警告以便于用户迁移；对于导出的 `Themes` 静态对象和 `mergeThemes` 工具函数，需要做一些 ESM 模块的测试；此外还有一些文档和测试用例需要更新。这个功能看起来需要一些时间，现在我已经有了一些想法，晚些时候我会尝试实现它。

**Comment by unix** [comment]
新的主题系统已经发布，使用 `yarn add @geist-ui/react@latest` 尝试最新版本，与之对应的主题参考文档也已更新。
