### ISSUE TITLE
Duplicate ts declaration

### ISSUE THREAD

**Issue by GuichiZhao** [geist-org/react#366]
In  [this file](https://github.com/zeit-ui/react/blob/master/components/styles/themes/index.ts) I see the declaration of the interface

In [this file](https://github.com/zeit-ui/react/blob/master/components/styles/themes/default.ts) I see the implementation of the interface

My suggestion:
Infer the interface using the implementation, Note that they are configuration constant, and no one else can ever implement the interface i.e.

`export type ZeitUIThemesPalette=typeof palette`

**Comment by unix** [comment]
This can be done together with #353 .
