### ISSUE TITLE
add an update action on Table's operation

### ISSUE THREAD

**Issue by wcastand** [geist-org/react#369]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  - I wonder if it would be hard to add a new action in the operation for the Table component. An update operation to update the data of the specific row without deleting it(when i try to update the full set of data, the table delete the rows and becomes empty, not sure if it's a bug or not)

- Could also be a way to force re-render if that makes sense, i have a case where my action is to archive or restore a client but i don't it to disappear from the table, i just want to update the action, when i try to update the data set, the Table component becomes empty so unless i reload, the data are not up-to-date.

### Examples

```jsx
() => {
  const operation = (actions, rowData) => {
    return <Button type="warning" auto size="mini" onClick={() => actions.update({...rowData.rowValue, description: 'updated')}>Update</Button>
  }
  const data = [
    { property: 'type', description: 'Content type', operation },
    { property: 'Component', description: 'DOM element to use', operation },
    { property: <Text b>bold</Text>, description: 'Bold style', operation },
  ]
  return (
    <Table data={data}>
      <Table.Column prop="property" label="property" />
      <Table.Column prop="description" label="description" />
      <Table.Column prop="operation" label="operation" width={150} />
    </Table>
  )
}
```

**Comment by unix** [comment]
This is feasible from the point of view of implementation.
I will try to develop this feature locally,  if it doesn't have a big impact on the overall design, I think this is one of the features that can be added.
(I haven't had much time recently to develop new features, now we have an emergency that all the projects need to be migrated. #370 )

**Comment by wcastand** [comment]
Ok no problem, thanks for replying :) 
If i have some time i might look into it, see if i can make a Pr to make it easier for you if you think that can help?

**Comment by wcastand** [comment]
i was going to look into it but when i forked, there is already a `updateColumn` added? Did you work on it already?
