### ISSUE TITLE
[BIG CHANGES] We are about to migrate all projects

### ISSUE THREAD

**Issue by unix** [geist-org/react#370]
## Event content

All projects under the organization `zeit-ui` need to be migrated, the migration may have the following effects:

  - All projects are migrated to the new organization.
  - NPM's organization will also be migrated.
  - The documentation for all projects will change a lot.
  - Our site domain name will also be migrated.

**For users of this project, there is no impact. (However, when you upgrade `zeit-ui`, you may need to rename the dependency.)**

## Event cause

Vercel believes that open source projects or domain names that contain `zeit` names may infringe on their trademarks. We can't add `zeit` to the project name or domain name, for Vercel, this is not allowed. In order not to receive DMCA notification from GitHub, we have to make these migrations, even though the organization('zeit-ui') is open source, it doesn't do any business. 

I know it's a bit strange for every user, because you don't get a similar warning when you create an open-source project with [google](https://github.com/search?q=google&ref=opensearch) or [twitter](https://github.com/search?q=twitter&ref=opensearch) characters. But it's true. I got a letter from the COO of company Vercel, I'm very sorry for the trouble caused by the name change, but it's a change that has to be made. (Since they are all React related projects, the name of the organization may cause confusion, which is also one of the facts.)

## Plans for the future

Although we will make a big move in the coming week, our maintenance of the project will not change. If you are planning to use this project, don't worry at all, that doesn't stop us from being enthusiastic about open source.

<del>If you have any ideas about our **new name** or **this migration**, please leave a message here and let me know.</del>

----

**Update after 2020-08-24**:

  - All the projects have been migrated to the organization [geist-org](https://github.com/geist-org).
  - The packages of NPM are migrated to [geist-ui](https://www.npmjs.com/package/@geist-ui/react).
  - The content of the document has changed greatly.

This migration may cause some link invalidation and pointing error, if you find any errors, please leave a message here.

**Comment by treykaws** [comment]
Unfortunate, but can definitely see where they're coming from. I think this is a great opportunity to figure out your own identity for the library and the direction you plan to head in the future.

**Comment by firede** [comment]
How about `TIEZ`?

> **TIEZ**
> stands for "take it easy". it means take care of yourself. used when saying goodbye to somebody, friend or stranger. only used online. pronounced 'tee-es'

**Comment by unix** [comment]
> How about `TIEZ`?

That sounds good, added to the reserve list.

**Comment by 7ma7X** [comment]
Though I like the sound and meaning of `TIEZ`, I'd like to propose another name `TOKI` 🥰 .

`ZEIT` stands for "time" in Deutsch. `TOKI` stands for "time"  in Japanese.

**Comment by unix** [comment]
@7ma7X This is the best I've ever seen! 👍 
Unfortunately, the migration is already part of it, a new organization is already running: [geist](https://github.com/geist-org).
If I had a new project, I would definitely use `TOKI`, it's looks so cool!

**Comment by 7ma7X** [comment]
@unix Oh I should have told you earlier 😭 .
