### ISSUE TITLE
Type of image component's width & height is number but docs shows it as a string.

### ISSUE THREAD

**Issue by kasipavankumar** [geist-org/react#373]
# About `docs`

This is a document site related issue.

### Languages

  - [x] English
  - [ ] Chinese

#### The Issue

Greetings.

In the documentation page of the [Image](https://react.zeit-ui.co/en-us/components/image#apis), the API table shows the type of width & height as `number` but in the examples, they are set as `string`, which raises an error in TypeScript `(.tsx)` files.

#### Example

```javascript
{/* This throws an type error. */}
<Image width="500" height="500" src="..." />

{/* This works fine. */}
<Image width={500} height={500} src="..." />
```

#### TypeScript Config

Here is the `tsconfig.json` file.

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve"
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

Just wanted to clarify if this is a typo or is there anything that I'm missing?
Thank you.

### Page Links (Optional)

1. [Image API](https://react.zeit-ui.co/en-us/components/image#apis)
2. [Documentation Page](https://github.com/zeit-ui/react/blob/master/pages/en-us/components/image.mdx)

**Comment by unix** [comment]
Thanks, this looks like a documentation error, I'll fix it after the migration.

**Comment by kasipavankumar** [comment]
No problem. 
I'd be happy to do a PR if that doesn't interrupt the migration process.

Thanks.

**Comment by unix** [comment]
@kasipavankumar  ❤️ Now you can create PR at any time.

**Comment by kasipavankumar** [comment]
Just created a PR.
Thank you.
