### ISSUE TITLE
Missing attribute name on Checkbox component

### ISSUE THREAD

**Issue by wcastand** [geist-org/react#375]
# Bug report 🐞

## Version & Environment

  - Version of browser: Version 84.0.4147.125 (Official Build) (64-bit)
  - Version of `zeit-ui/react`: ^1.8.1

## Expection

The behavior I expect is for me to be able to use the attribute name on the checkbox input component.

## Actual results (or Errors)

I got an error: i get an error saying name is doesn't exist on this component.

```
Type '{ children: string; name: string; checked: boolean; onChange: (e: CheckboxEvent) => void; }' is not assignable to type 'IntrinsicAttributes & Partial<{ disabled: boolean; initialChecked: boolean; size: "small" | "mini" | "medium" | "large"; className: string; value: string; }> & Pick<...> & Pick<...> & { ...; }'.
  Property 'name' does not exist on type 'IntrinsicAttributes & Partial<{ disabled: boolean; initialChecked: boolean; size: "small" | "mini" | "medium" | "large"; className: string; value: string; }> & Pick<...> & Pick<...> & { ...; }'.
```

**Comment by unix** [comment]
Can you show your code or provide an online example?

**Comment by unix** [comment]
Try version `v2.0.1`: `yarn add @geist-ui/react@2.0.1`.

**Comment by wcastand** [comment]
all good thank, that was super fast !
