### ISSUE TITLE
Modals not vertically centered on mobile browsers

### ISSUE THREAD

**Issue by bryanhpchiang** [geist-org/react#380]
# Bug report 🐞

## Version & Environment

  - Version of browser
  - Version of `geist-ui/react`

Version 84.0.4147.135 (Official Build) (64-bit)
^1.8.0-canary.7

## Expection

The behavior I expect is ...

On mobile browers (iOS) Safari, Chrome, modals should be vertically centered.

## Actual results (or Errors)

Modals are not vertically centered - due to the mobile top and bottom menu bars? Below is an example illustrating this behavior:

![IMG_2867](https://user-images.githubusercontent.com/10623745/91650447-8d6ab100-ea34-11ea-911a-2b82bed66c27.PNG)

**Comment by bryanhpchiang** [comment]
To reproduce: open https://react.geist-ui.dev/en-us/components/modal on iOS Safari, click on "Open Modal". Top margin is taller compared to bottom margin.

**Comment by harshcut** [comment]
This must be the result of the browser panel(s). The same effect can be seen in Chrome. But since Chrome doesn't have a bottom accessibility panel, the effect is not so prominent.

**Comment by bryanhpchiang** [comment]
Makes sense — might be same reason why 100vh doesn't work on mobile.

**Comment by unix** [comment]
It looks like a problem caused by height, and I'm following up.

**Comment by unix** [comment]
This is a compatibility issue, but there is no good solution at present. I've refactored some of the layout logic of `Modal` to make sure it works in a variety of environments, fortunately, there is no change in the user API.

You can see this change here: #382 , I added a new example to the document, and you can see how the changes work on your device, If everything goes well, please let me know that I will merge and release a new version.

**Comment by bryanhpchiang** [comment]
Just tested it out on my own device, it's now vertically centered even if bottom menu bar is present or not. The only issue is that on Safari/Chrome, the bottom menu bar is present on page load, modal is fine; however, once I scroll down the bottom menu bar disappears, so the modal is no longer vertically centered.

But this is just a minor edge case, overall it's a lot better — thanks for improving it!
