### ISSUE TITLE
Font settings

### ISSUE THREAD

**Issue by qo** [geist-org/react#384]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

Quick suggestion about font settings - to the best of my understanding, Geist uses the system font. On Windows, however, the system font is disgusting. Is it possible to standardize on a font across platforms?

For example - Vercel uses Inter, which has a similar to appearance to the Apple system font (SF).

**Comment by unix** [comment]
Good proposal. Looks like [inter-ui](https://www.npmjs.com/package/inter-ui) is great, I'll try to add it to the project.

**Comment by unix** [comment]
I noticed that these font packs are very bulky, what do you think of the way that we declare but not introduce:

  - The default declaration `Inter` is the highest priority font.
  - Do not package or force users to use any fonts.
  - Guide users in the document how to get the best experience under windows:

```jsx
# yarn add inter-ui
import 'inter-ui/inter.css';
```

----
I have tested it and found it feasible. It doesn't make too many changes, but it allows you to get the best experience. Do you have any point on this?

**Comment by bryanhpchiang** [comment]
Sounds good to me — looking forward to trying it out!

Best,
Bryan

Bryan Chiang <https://linkedin.com/in/bryanhpchiang> | (408) 819-6688

**Comment by qo** [comment]
Looks good to me!
