### ISSUE TITLE
Autocomplete.Option Interface Change

### ISSUE THREAD

**Issue by will-holley** [geist-org/react#386]
I interested in an update to the `Autocomplete.Option` type detailed below:

```javascript
type AutoCompleteOption = {
  label: string
  value: object
}
```

which would include changing [here](https://github.com/geist-org/react/blob/6a3988c9340542f97230466edb83b388e0007bbb/components/auto-complete/auto-complete.tsx#L119)

```javascript
const updateValue = (label: string, value: object) => {
    if (disabled) return
    setSelectVal(val)
    onSelect && onSelect(val)
    setState(label)
    inputRef.current && inputRef.current.focus()
  }
```

and [here](https://github.com/geist-org/react/blob/6a3988c9340542f97230466edb83b388e0007bbb/components/auto-complete/auto-complete.tsx#L132):

```javascript
const resetInputValue = () => {
    if (!disableFreeSolo) return
    if (!state || state === '') return
    // or another object equality comparison technique
    if (state.toString() !== selectVal.toString()) {
      setState(selectVal)
    }
  }
```

My intention is to pass objects into `onSelect`.  Please let me know what you think, @unix -- thanks!

**Comment by unix** [comment]
This issue will be closed because the content does not follow the template, you can open a new issue.

**Comment by will-holley** [comment]
Where is the template, @unix?  It did not pre-populate when the issue was created.
