### ISSUE TITLE
Add a clear options on Select component

### ISSUE THREAD

**Issue by wcastand** [geist-org/react#388]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  - Would be nice to be able to add a `clearable` option to Select.
Not sure what we would like to do with that on single value but on the multiple Select, we could maybe add an icon (cross) to remove the option so you don't need to go into the list to remove an option.

Not sure if we want the option to be on the `Select.Option` or `Select` component.

### Examples

```jsx
 <GeistSelect multiple>
       {options.map((option) => (
           <GeistSelect.Option value={option.value} clearable>
               {option.label}
           </GeistSelect.Option>
        ))}
 </GeistSelect>
```

**Comment by unix** [comment]
I agree with you that adding `clearable` to `multiple-mode` helps the user experience.

**Comment by wcastand** [comment]
You think it should be by default when multiple is true?
or to add it to the Option component?

**Comment by wcastand** [comment]
Been thinking a bit about this, the way i would do it is:

- when `multiple` is true, `clearable` is true by default (i think it's a good UX to get a clearable select by default)
- when `multiple` is true, you can pass `clearable` to false if you don't want it
- if you pass `clearable` as a prop to select without `multiple`, we just ignore it

Does that makes sense for you or you would like something different?

**Comment by unix** [comment]
You're absolutely right. I totally agree with you on this feature. @wcastand 👍

**Comment by wcastand** [comment]
The feature was merged in `rc` so we can probably close this issue or you want to wait for the release on npm? @unix

**Comment by unix** [comment]
We can close it now, and pre-release `v2.1.0-canary.2` is out.
