### ISSUE TITLE
Be able to add custom style to row(tr) on Table component

### ISSUE THREAD

**Issue by wcastand** [geist-org/react#389]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

Would be nice to be able to add custom style to `<tr>` in the `Table` component. In my case i want to align on top of the row and i can't do that properly.

If you look at the third row on the screenshot, we can see it's centered but can't manage that without accessing the row style unless i'm missing something.

### Others (Optional)
<img width="1072" alt="Screenshot 2020-10-03 at 16 14 28" src="https://user-images.githubusercontent.com/2178244/94993799-ba5e3680-0593-11eb-933a-8a042466ff82.png">

**Comment by unix** [comment]
released in v2.2.0.
