### ISSUE TITLE
Support React Native

### ISSUE THREAD

**Issue by nandorojo** [geist-org/react#390]
# Feature request 🚀
 
  - [x] It's just a suggestion

### Expected

I'd love to use this on React Native!

### Examples

Same API as React, for the most part.

### Others (Optional)

I'm the maintainer of [dripsy](https://github.com/nandorojo/dripsy), a responsive design system for React Native. It's a bit more low-level than geist, it's mostly theme-able components with responsive styles. I'm looking for a UI library to build for React Native, using Dripsy as the UI primitives, and I think geist is just amazing. Is there interest for adding React Native support at some point?

I suppose I could try to remake the existing react components in native.

**Comment by unix** [comment]
I don't have this plan for the time being (I don't have so much time for maintenance), but if you or anyone is willing to create an open-source library related to react-native, I'd like to put your project connection on the home page.

**Comment by nandorojo** [comment]
@unix Sounds good. I’m going to slowly build it into my app, so once I make some real headway I’ll try to turn it into its own repo.
