### ISSUE TITLE
Description API change

### ISSUE THREAD

**Issue by arguiot** [geist-org/react#393]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  - The description should use its children instead of the `content` parameter

### Examples

```jsx
// From
<Description title="Description" content="Content" />
// To
<Description title="Description">Content</Description>
```

**Comment by unix** [comment]
This is just different styles. If the two styles achieve the same function, there is no difference:

```jsx
<Description title="Description" content="Content" />
```
```jsx
<Description>
  <Description.Title>Description</Description.Title>
  <Description.Content>Content</Description.Content>
</Description>
```

For future extensibility and functionality suggestions, please reopen this issue if you want to discuss it.
