### ISSUE TITLE
A skeleton component

### ISSUE THREAD

**Issue by h2o7** [geist-org/react#410]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  - A skeleton component, since this seems to be the loading state recommendation from most developers. 

### Examples

https://material-ui.com/components/skeleton/#skeleton

**Comment by unix** [comment]
This component will not be added in the near future. #256

**Comment by logicaltitan** [comment]
A note for others, I ended up using tailwind and MUI implmentation of skeleton as a reference to build this for myself.

- https://tailwindcss.com/docs/animation
- https://github.com/mui-org/material-ui/blob/master/packages/material-ui-lab/src/Skeleton/Skeleton.js
