### ISSUE TITLE
Card margin doesn't work in className

### ISSUE THREAD

**Issue by MrTierrin** [geist-org/react#417]
# Bug report 🐞
When i use the `className` prop in the Card component and i set it to my class "mt-3" (margin-top: 15px in css) the card doesn't get my margin.

## Version & Environment

  - Version of browser
  - Version of `geist-ui/react`: 2.1.0-canary.2

## Expection

The behavior I expect is the card with margin-top

## Actual results (or Errors)
![image](https://user-images.githubusercontent.com/51929737/99466526-8ef89680-290a-11eb-9ceb-d552ccfd6829.png)

**Comment by unix** [comment]
[Here(#317)](https://github.com/geist-org/react/issues/317) can to help you.
