### ISSUE TITLE
classNames proposition

### ISSUE THREAD

**Issue by PaulPCIO** [geist-org/react#419]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

- Each component should have a  unique identifying classNames.
- With common classNames like `card, btn, layout`, they might clash with other design systems and styles.
- Theming config should allow to customise className prefix (default `geist`)

### Proposition
| Component       | className             |
| --------------- | --------------------- |
| Grid            | geist-grid            |
| Layout          | geist-layout          |
| Page            | geist-page            |
| Spacer          | geist-spacer          |
| Card            | geist-card            |
| Collapse        | geist-collapse        |
| Fieldset        | geist-fieldset        |
| Auto-Complete   | geist-auto-complete   |
| Button-Group    | geist-button-group    |
| Checkbox        | geist-checkbox        |
| Input           | geist-input           |
| Radio           | geist-radio           |
| Select          | geist-select          |
| Slider          | geist-slider          |
| Textarea        | geist-textarea        |
| Toggle          | geist-toggle          |
| Avatar          | geist-avatar          |
| Badge           | geist-badge           |
| Capacity        | geist-capacity        |
| Description     | geist-description     |
| Display         | geist-display         |
| Dot             | geist-dot             |
| File-Tree       | geist-file-tree       |
| Image           | geist-image           |
| Keyboard        | geist-keyboard        |
| Popover         | geist-popover         |
| Table           | geist-table           |
| Tag             | geist-tag             |
| Tooltip         | geist-tooltip         |
| User            | geist-user            |
| Loading         | geist-loading         |
| Modal           | geist-modal           |
| Note            | geist-note            |
| Progress        | geist-progress        |
| Spinner         | geist-spinner         |
| Toast           | geist-toast           |
| Breadcrumbs     | geist-breadcrumbs     |
| Link            | geist-link            |
| Pagination      | geist-pagination      |
| Tabs            | geist-tabs            |
| Button-Dropdown | geist-button-dropdown |
| Divider         | geist-divider         |
| Snippet         | geist-snippet         |

**Comment by unix** [comment]
Currently, our `className` is compiled as a jumbled string of code to ensure no conflicts:
```
// input:
.btn { ... }

// output:
.btn.jsx-2034276802
```
But I'm still in favor of your proposal, which in a way ensures the uniformity of our naming system.
This will take some time to work out, so if you are interested, you can take away this issue. Or later I will create a PR.

**Comment by PaulPCIO** [comment]
Excellent will keep an eye out 👀
