### ISSUE TITLE
Doesn`t work className attribute for Text component.

### ISSUE THREAD

**Issue by kvandake** [geist-org/react#421]
# Bug report 🐞

## Version & Environment

  - any browser
  - 2.1.0-canary.2

## Expection

When I write custom styles for stock components, the styles doesn`t apply.

## Actual results (or Errors)

I got an error:

```tsx
<>
  <Text h1 size="4rem" className={"title"}>
      The React Framework for Production
  </Text>
  <style jsx>{`
    .title { 
      text-align: center;
    }
  `}</style>
</>
```

**Comment by unix** [comment]
[Here(#317)](https://github.com/geist-org/react/issues/317) can to help you.
