### ISSUE TITLE
showcase

### ISSUE THREAD

**Issue by maxcutie** [geist-org/react#433]
=) https://pfps.icu/

**Comment by hansfpc** [comment]
@maxcutie what component have you used for this mesage?
![image](https://user-images.githubusercontent.com/12705403/103713777-e676c280-4f9b-11eb-8e71-027c3ca0311f.png)

**Comment by maxcutie** [comment]
> @maxcutie what component have you used for this mesage?
> ![image](https://user-images.githubusercontent.com/12705403/103713777-e676c280-4f9b-11eb-8e71-027c3ca0311f.png)

Hello! I used react-hot-toast (https://github.com/timolins/react-hot-toast)  :)
