### ISSUE TITLE
Portal placement wrong when I scroll

### ISSUE THREAD

**Issue by philmetzger** [geist-org/react#435]
# Bug report 🐞

## Version & Environment

  - Version of browser
  - -  79.0.3945.88 (Official Build) (64-bit) (ubuntu)
  - Version of `geist-ui/react`
  - - 2.1.0-canary.2

## Expection

When I click on a button to show a portal dialog, it should point at the button

## Actual results (or Errors)

When I scroll down the page, then click on a button to display a portal, then the modal is pointing at the wrong thing.

```
<Popover content={this.getEditPopoverContent()}>
    <Button iconRight={<Edit2/>} auto={true} size="mini" ghost={true} shadow={true}/>
</Popover>
```

Correct:
![image](https://user-images.githubusercontent.com/4325631/104513607-2d923280-55f0-11eb-8521-a647038171e5.png)
Incorrect (as soon as the page scroll changes):
![image](https://user-images.githubusercontent.com/4325631/104513622-35ea6d80-55f0-11eb-9f5d-d14bfdea2e72.png)

I am guessing the portal is globally rendered and not locally to the element it should be triggered from?

Is this a bug or have I done something wrong

**Comment by unix** [comment]
I'm not sure, I have not succeeded in reproducing the problem you describe, could you try to provide an online example if possible. (Codesandbox or GitHub CodeSpaces)
