### ISSUE TITLE
Custom breakpoints doesn't work

### ISSUE THREAD

**Issue by muxinqi** [geist-org/react#471]
# Bug report 🐞

## Version & Environment

- Version of the browser

```bash
Google Chrome
Version 89.0.4389.82 (Official Build) (x86_64)
```

- Version of `geist-ui/react`

```bash
# yarn.lock

"@geist-ui/react@^2.1.3":
  version "2.1.3"
```

<br />

## Expectation

After customizing the breakpoint as follows:

```diff
import { GeistProvider, CssBaseline } from '@geist-ui/react'

+ const breakpoints = {
+    xs: { min: '0', max: '640px' },
+    sm: { min: '640px', max: '768px' },
+    md: { min: '768px', max: '1024px' },
+    lg: { min: '1024px', max: '1536px' },
+    xl: { min: '1536px', max: '10000px' },
+  }

function MyApp({ Component, pageProps }) {
  return (
-   <GeistProvider>
+   <GeistProvider theme={{ breakpoints: breakpoints }}>
    <CssBaseline />
    <Component {...pageProps} />
  </GeistProvider>
  )
}

export default MyApp
```

Besides, I added some responsive button to visualizing this problem:
(code just like Geist-UI's Documents👇)

![image.png](https://i.loli.net/2021/03/09/MqpGc2ekWiVPSOH.png)

<br />

The behavior I expect is the minimum breakpoints of `md` changed from `900px`(default) to `768px`.

<br />

## Actual results (or Errors)

I got an error:

```bash
# nothing
```

But in fact, it is not. It remains at the default value (900px).👇

![custom breakpoints won't work](https://i.loli.net/2021/03/09/B23iHCVdZtGwEmP.gif)

<br />

## Reproduce Step

1. Fetch Next.JS scaffold and install `@geist-ui/react`
```bash
$ npx create-next-app nextjs-geist-ui-demo
$ cd nextjs-geist-ui-demo
$ npm i @geist-ui/react
```
2. Import package and use Geist UI components just like [installation documents](https://react.geist-ui.dev/en-us/guide/installation) said.
3. Add custom breakpoints and some buttons.

then 

```bash
$ npm run dev
```

Just check the following repo to review the source code and Vercel Demo for a quick inspection.

<br />

## Demo

Repository: https://github.com/muxinqi/nextjs-geist-ui-demo
Vercel Demo: https://nextjs-geist-ui-demo.vercel.app/

**Comment by unix** [comment]
The documentation on custom breakpoints is outdated, sorry about that, I've updated the documentation [here](https://github.com/geist-org/react/pull/478).

Now you can refer to [Grid's documentation](https://react.geist-ui.dev/en-us/components/grid) for breakpoint customization.
