### ISSUE TITLE
Position: Sticky does not work with CSS Baseline (NextJS)

### ISSUE THREAD

**Issue by PR91** [geist-org/react#485]
# Bug report 🐞

## Version & Environment

  - Version of browser: Chrome 89.0.4389.90
  - Version of `geist-ui/react`: 2.1.3 (NextJS)

## Expection

The div container should stop scrolling with the page.

## Actual results (or Errors)

The div container continues scrolling with the page ignoring the sticky directive on the CSS.

Removing CssBaseline component from _app solves the issue, but breaks the framework styling.

Please advise.

**Comment by unix** [comment]
Add this styles will solve this issue:
```
#__next {
    overflow-x: unset;
}
```
