### ISSUE TITLE
Position: Sticky does not work with CSS Baseline (NextJS) #485

### ISSUE THREAD

**Issue by PR91** [geist-org/react#487]
# Bug report 🐞

Sorry for resubmitting the issue but I was not able to re-open the original one. 
Thank you for the quick response, but it did not help. 

## Version & Environment

  - Version of browser 89.0.4389.90
  - Version of `geist-ui/react`2.1.3 (NextJS)

## Expection

The div container should stop scrolling with the page.
This time I made a video: https://streamable.com/pd0wgk

## Actual results (or Errors)

The div container continues scrolling with the page ignoring the sticky directive on the CSS.

Removing CssBaseline component from _app solves the issue, but breaks the framework styling.

Please advise.

**Comment by unix** [comment]
I created an [example](https://codesandbox.io/s/geist-ui-sticky-o71s3) and it looks fine, can you provide a reproducible online example?
