### ISSUE TITLE
Option to disable displaying value in slider dot

### ISSUE THREAD

**Issue by robertsamarji** [geist-org/react#491]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  - Slider component

It would be useful to have an option to disable the slider value value appearing in the slider dot.

### Examples

```
<Slider
  showMarkers
  min={1}
  max={5}
  showValue={false}
/>
```
### Others (optional)

<img width="328" alt="Screenshot 2021-03-25 at 21 51 45" src="https://user-images.githubusercontent.com/26310556/112548619-6864d380-8db4-11eb-8705-6558da5fedbb.png">

**Comment by Deep-Codes** [comment]
@robertsamarji Instead of `showValue` i used `hideValue` let me know if anything else is needed!

<img width="786" alt="Screenshot 2021-03-30 at 12 54 22 PM" src="https://user-images.githubusercontent.com/61158210/112949613-0f4fc380-9157-11eb-9204-c769357462e9.png">

**Comment by robertsamarji** [comment]
Hey @Deep-Codes, where are you getting this from? I can't seem to find any "hideValue" attribute in the docs nor in the code for the React version of this component.

**Comment by robertsamarji** [comment]
Hey, thank you @Deep-Codes! I will wait for your pull request to merge and give it a go!
