### ISSUE TITLE
Drawer

### ISSUE THREAD

**Issue by prabhuomkar** [geist-org/react#501]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  - Is it possible to get [Drawer from Vercel Design](https://vercel.com/design/drawer)

### Examples

```jsx
<Drawer show={active} onDismiss={() => ...}>
    ...
</Drawer>
```

PS: Thanks to the maintainers, geist-ui is the best ❤️ and we are using it in production :)

**Comment by unix** [comment]
Sounds good, I will come to implement this component. (about 1 to 2 weeks.)

**Comment by prabhuomkar** [comment]
Hey @unix is there a public roadmap available?

**Comment by stormy251** [comment]
Hi there, I'm just here to echo what @prabhuomkar said in their PS 😄 

I love geist-ui!! Thank you so much for all the hard work and effort!

**Comment by ofekashery** [comment]
Added in [``v2.2.0``](https://github.com/geist-org/react/releases/tag/v2.2.0) (#575).

[**💡 Drawer Documentation**](https://react.geist-ui.dev/en-us/components/drawer)

**Comment by prabhuomkar** [comment]
Thank you so much!
cc: @akshaypithadiya
