### ISSUE TITLE
Footer component

### ISSUE THREAD

**Issue by Deep-Codes** [geist-org/react#502]
# Feature request 🚀

  - [x] I will create Pull Request
  - [x] It's just a suggestion

### Example

[Refer This for Example](https://vercel.com/design/footer)

I needed this component so I tried and have 1 example ready:

![Footer](https://user-images.githubusercontent.com/61158210/113381176-f08e3e80-939b-11eb-9081-2838e9cbbeeb.gif)

So let me know if it's needed I would start working on it.

**Comment by unix** [comment]
Looks very nice 👍 , I think this component can be merged.

**Comment by ofekashery** [comment]
Please see https://github.com/geist-org/react/pull/505#issuecomment-863481366.
