### ISSUE TITLE
How do I implement Page navigation using the Tabs Components?

### ISSUE THREAD

**Issue by Twoy519** [geist-org/react#506]
# About `docs`
Hi! What's the easiest way to implement Tab Components just to link to other pages in the way that both vercel.com and react.geist-ui.dev do? I'm surprised this isn't an example in the Tab Component library?

### Languages

  - [x] English
  - [ ] Chinese

### Description
Hi! What's the easiest way to implement Tab Components just to link to other pages in the way that both vercel.com and react.geist-ui.dev do? I'm surprised this isn't an example in the Tab Component library?

**Comment by ofekashery** [comment]
@Twoy519, Do you use Next.js?

**Comment by Twoy519** [comment]
Yeah Next.js

**Comment by Twoy519** [comment]
@ofekashery Yes I am using Next.js

**Comment by Deep-Codes** [comment]
@Twoy519 I think you can refer to the `code` for the implementation

[Tab Menu](https://github.com/geist-org/react/blob/master/lib/components/menu/menu-sticker.tsx)

https://github.com/geist-org/react/blob/18c1afbc14d8d7ba7c6352d6a0084211d29d6f07/lib/components/menu/menu-sticker.tsx#L43

**Comment by ofekashery** [comment]
Hi @Twoy519, it might help you:

```tsx
import React from 'react';
import { useRouter } from 'next/router';
import { Tabs } from '@geist-ui/react';

const Menu = () => {
  const router = useRouter();

  return (
    <Tabs value={router.pathname} onChange={(route) => router.push(route)}>
      <Tabs.Item label="Overview" value="/" />
      <Tabs.Item label="Projects" value="/projects" />
      <Tabs.Item label="Integrations" value="/integrations" />
      <Tabs.Item label="Activity" value="/activity" />
      <Tabs.Item label="Domains" value="/domains" />
      <Tabs.Item label="Usage" value="/usage" />
      <Tabs.Item label="Settings" value="/settings" />
    </Tabs>
  );
};

export default Menu;
```
