### ISSUE TITLE
No option specified to change color of Radio Component

### ISSUE THREAD

**Issue by shubham-web** [geist-org/react#507]
# About `Radio Components`
[Radio Components](https://react.geist-ui.dev/en-us/components/radio) page does not specify how to change the color as we do with other components by specifying jsx attr eg. type, color to success, success-light, secondary etc. It's not even in customization settings JSON.

It's useful when we want Radio Button to appear as the site theme.

**Comment by gepd** [comment]
I've pushed a PR to fix this and the same problem in other components
