### ISSUE TITLE
radio component's fill doesn't overlap correctly

### ISSUE THREAD

**Issue by Deep-Codes** [geist-org/react#508]
# Bug report 🐞

## Version & Environment

  - Version of browser:
  - Version of `geist-ui/react`: `2.1.4`

[Reproduction CodeSandbox](https://codesandbox.io/s/mystifying-mcnulty-hf1o1?file=/pages/index.js)

## Expected Behaviour

Ideally the Filled Circle Should Overlap the Radio Completly Like this:

<img width="162" alt="Screenshot 2021-04-08 at 11 12 49 AM" src="https://user-images.githubusercontent.com/61158210/113974338-5cb8e880-985b-11eb-8854-4462d6f58e11.png">

## Actual results (or Errors)

<img width="163" alt="Screenshot 2021-04-08 at 11 13 58 AM" src="https://user-images.githubusercontent.com/61158210/113974421-870aa600-985b-11eb-8398-a5d9f986439e.png">

If you see closely it doesn't overlap in the way as it is in the docs.

**Comment by unix** [comment]
It looks like there may be a problem with the layout alignment of the option itself 😿

**Comment by Bowen7** [comment]
Add `box-sizing: border-box;` will fix it.

**Comment by Deep-Codes** [comment]
@Bowen7 Yeah Thanks Works, is this a problem with the library or just the `reset css` is not applied ?

**Comment by Bowen7** [comment]
> @Bowen7 Yeah Thanks Works, is this a problem with the library or just the `reset css` is not applied ?

I think this is a problem with the library.

**Comment by unix** [comment]
@Deep-Codes 
I tried several examples but still did not reproduce the issue. 😼
I guess it might have something to do with the parity of the pixels, can you provide an online example?

**Comment by Deep-Codes** [comment]
> @Deep-Codes
> I tried several examples but still did not reproduce the issue. 😼
> I guess it might have something to do with the parity of the pixels, can you provide an online example?

Looks like it is fixed now 😅 but It was there for sure.

I had posted an online example, but it is fixed in that too.
