### ISSUE TITLE
disableBackdropClick not working when there is no Modal.Action element

### ISSUE THREAD

**Issue by dawiddyd** [geist-org/react#526]
# Bug report 🐞

`disableBackdropClick` prop not working when there is no `Modal.Action` element.

## Version & Environment

  - Version of browser - Chrome 90.0.4430.93
  - Version of `geist-ui/react` - 2.1.0-canary.2

## Expected Behaviour

Modal shouldn't close on backdrop click when no `Modal.Action` elements. 

## Actual results (or Errors)

The modal is closing.

**Comment by unix** [comment]
This is actually a feature that disables the user from ever displaying popups. This doesn't look good now and may confuse developers.
I removed this feature in #532  to ensure it meets developer expectations, this change involves a change in behavior as will be released in the next version.
