### ISSUE TITLE
Sidebar, Playground, Navbar, and other Doc website elements

### ISSUE THREAD

**Issue by andreostrovsky** [geist-org/react#551]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  * Could the elements from the documentation website be added to the library? The sidebar for example would be really useful. Same with the sticky navbar.
  * The playground component with the expandable code editor looks like an extension of `<Fieldset>`, just with a copy button and collapsible footer. Perhaps that functionality could be rolled into it with a `collapse` prop?
    - Add `borderless` prop to `<Button>` to enable recreating the copy button from the playground.
    - Could `<Textarea>` please get a `code` prop to style the text like in `<Code>` or `<Snippet>`? I've been doing this with CSS classes, but a simple prop would be really convenient.

### Examples

```js
<Fieldset>
    ...
  <Fieldset.Footer collapse>
    <Fieldset.Footer.Status>
      <Text small>Code Editor</Text>
    </Fieldset.Footer.Status>
    <Fieldset.Footer.Actions>
      <Button iconRight={<Copy />} auto borderless size="small" />
    </Fieldset.Footer.Actions>
    <Fieldset.Footer.Content>
      <Textarea width="100%" code />
    </Fieldset.Footer.Content>
  </Fieldset.Footer>
</Fieldset>
```

Thanks and much ❤️, geist-ui is the best

**Comment by unix** [comment]
These functions are a kind of customization, not the smallest unit that can be abstracted in the layout, and we don't want to add these elements to the component library for now.
Thank you for the kind words, sorry this feature is not available.
