### ISSUE TITLE
Lowercase button text

### ISSUE THREAD

**Issue by Shadowport** [geist-org/react#554]
# Bug report 🐞

## Version & Environment

  - Version of browser: `Any`
  - Version of `geist-ui/react`:  `2.1.5`

## Expected Behaviour

The behavior I expect is ...

Geist is simply awesome, and the capitalized Button Text is great, but is there a way to disable it for special words? Such like "iOS". 

## Actual results (or Errors)

<img width="811" alt="Screen Shot 2021-06-05 at 5 22 18 PM" src="https://user-images.githubusercontent.com/81877702/120886966-1990b100-c623-11eb-9840-e24a9ed2c3da.png">

**Comment by unix** [comment]
You can simply use nested components to control the texts, refer to [online example](https://codesandbox.io/s/cranky-dewdney-wvpn6?file=/src/app.js)
