### ISSUE TITLE
React@17 and Nextjs

### ISSUE THREAD

**Issue by Frank-vdm** [geist-org/react#555]
# Bug report 🐞
Im using the create-next-app example found in this repo to look ash the feasibility of using these components in my Nextjs app. the example works fine with react 16, but the moment I upgrade react to react 17 running the app fails with:
Error: Invalid hook call.

## Version & Environment

Safari: Version 14.1.1 (16611.2.7.1.4)
Firefox: 88.0.1 (64-bit)
Firefox: 89.0 (64-bit) (Firefox updated with testing)
geist-ui/react: Version 2.1.5
React: Version 17.0.2
React-DOM: Version 17.0.2

## Expected Behaviour

The behavior I expect is ...
I Should be able too update React to 17 without everything breaking

## Actual results (or Errors)

I got an error:
<img width="768" alt="Screenshot 2021-06-08 at 15 06 18" src="https://user-images.githubusercontent.com/26402451/121190186-15ef6b00-c86b-11eb-9446-d51a951d4477.png">

create-next-app example with 
package.json update
```
"react": "17.0.2",
"react-dom": "17.0.2",
```

**Comment by unix** [comment]
This issue has been fixed in the `canary` version: `yarn add @geist-ui/react@canary`

**Comment by Frank-vdm** [comment]
very much appreciated
