### ISSUE TITLE
希望推出一个类似antd的form组件，

### ISSUE THREAD

**Issue by cnly1987** [geist-org/react#559]
日常工作中，处理最多的就是表单。
antd的form组件就非常的方便。  https://ant.design/components/form-cn/

`<Form
      name="basic"
      initialValues={{ remember: true }}
      onFinish={onFinish}
      onFinishFailed={onFinishFailed}
    >
      <Form.Item
        label="Username"
        name="username"
        rules={[{ required: true, message: 'Please input your username!' }]}
      >
        <Input />
      </Form.Item>

      <Form.Item
        label="Password"
        name="password"
        rules={[{ required: true, message: 'Please input your password!' }]}
      >
        <Input.Password />
      </Form.Item>

      <Form.Item {...tailLayout} name="remember" valuePropName="checked">
        <Checkbox>Remember me</Checkbox>
      </Form.Item>

      <Form.Item {...tailLayout}>
        <Button type="primary" htmlType="submit">
          Submit
        </Button>
      </Form.Item>
    </Form>`

geist-org的风格非常喜欢， 希望能够更好~

**Comment by unix** [comment]
没有增加表单的计划。这因为定位不太一样，Geist UI 并不是为后台 (或是 Dashboard) 实现的组件系统，所以不会在这方面花费很多时间。我们希望能够把更多的维护成本放在表达、排版、展示上。
感谢你的支持！
