### ISSUE TITLE
Sticky Header With Blurry Transparent Background

### ISSUE THREAD

**Issue by ninecodes** [geist-org/react#560]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  - Sticky header that also has a blurry background just like the one on Vercels website

### Examples
Here we can see how it looks like
![image](https://user-images.githubusercontent.com/31674307/122445378-c95e0b00-cfa1-11eb-997a-786085bff7ec.png)

Code example could look like:

```jsx
<Page.Header sticky blur>
    <h2>Header</h2>
</Page.Header>
```

**Comment by unix** [comment]
The Page component is just a layout container that does not and will not carry any business functionality.
