### ISSUE TITLE
Icon colour doesnt change

### ISSUE THREAD

**Issue by Milo123459** [geist-org/react#580]
# Bug report 🐞

## Version & Environment

  - Version of browser: Chrome Latest
  - Version of `geist-ui/react`: Latest

## Expected Behaviour

The behavior I expect is ...

When I do 
```
<Home color="#123" />
```
it should change colour, but it doesn't. This also applies for sizing. I'm trying to change the size of breadcrumbs and it isn't changing.

## Actual results (or Errors)

Colour doesn't change

https://github.com/Milo123459/website/tree/Milo123459/issue97 < code

**Comment by Milo123459** [comment]
I also have a question, I need to disable the hover effect in the breadcrumbs when using next link. I set aria-disabled but that doesn't stop the animation. Any ideas?

**Comment by unix** [comment]
I clone your project and changed the color and everything looks fine.
![image](https://user-images.githubusercontent.com/11304944/124435638-c471c780-dda7-11eb-8499-b9451a043f17.png)
![image](https://user-images.githubusercontent.com/11304944/124435658-c89de500-dda7-11eb-9012-075668f4f8d5.png)

If you are still experiencing this issue, please provide an online example that reproduces the problem. ([codesandbox](https://codesandbox.io/))

----
Also, if you want to change the CSS effect of the hover, use CSS to override the original style:
```
nav > a:hover {
  color: inherit;
}
```

**Comment by Milo123459** [comment]
Okay. What about the size of the breadcrumbs not changing?

**Comment by Milo123459** [comment]
I did <Breadcrums size="medium"> and nothing changed?

**Comment by unix** [comment]
@Milo123459 
As you can see, the `size` property accepts an enumerated value instead of a number or other string, please refer to the official website to modify it:

![image](https://user-images.githubusercontent.com/11304944/124440451-3993cb80-ddad-11eb-8366-dd65e5b64a73.png)

**Comment by Milo123459** [comment]
So I have to do:
```
size="medium"
```

**Comment by Milo123459** [comment]
I did, nothing changed. Can you take a look at my code and see what I did wrong?

**Comment by unix** [comment]
In your project, everything looks great, do you need to check your code again?

![image](https://user-images.githubusercontent.com/11304944/124440729-84adde80-ddad-11eb-8316-f6d8dc004813.png)

**Comment by Milo123459** [comment]
I don't think so. In my `_app.tsx` I have the size property set to medium yet the size doesn't change. I really don't understand

**Comment by unix** [comment]
I have changed, checked, and previewed your project and everything looks fine, please refer to the above screenshot.

Back to the original question, if you are still troubled by this, please provide [an online example](https://codesandbox.io/s/geist-ui-typescript-65td1) so that I can help you figure out why.

**Comment by Milo123459** [comment]
I'm not troubled by the original problem, just the size not changing.

Here is a preview deployment, built by Vercel: https://milo123459-h41bfgr6a-salvage.vercel.app/

As you can see, the breadcrumbs size didn't change. Still ridiculously confused.

**Comment by unix** [comment]
if you are still troubled by this, please provide [an online example](https://codesandbox.io/s/geist-ui-typescript-65td1) so that I can help you figure out why.

**Comment by Milo123459** [comment]
Well, it works when I try it online but not in my regular project.

**Comment by Milo123459** [comment]
In my next project, it doesn't change size. On the code sandbox, it does.

**Comment by Milo123459** [comment]
I guess it isn't a bug, but would you mind helping me out / figuring out why it doesn't work?
