### ISSUE TITLE
Dark mode causes visual bugs

### ISSUE THREAD

**Issue by Milo123459** [geist-org/react#582]
# Bug report 🐞

## Version & Environment

  - Version of browser Chrome Latest
  - Version of `geist-ui/react` Latest

## Expected Behaviour

The behavior I expect is ...

Colours to change, but not sizing & ordering of components.

## Actual results (or Errors)

Sizes change and positioning

Code: https://github.com/Milo123459/website

https://user-images.githubusercontent.com/50248166/124507225-4b816880-ddc5-11eb-9ff5-996d0dff9b09.mp4

Changes only apply when I refresh the page.

**Comment by sannajammeh** [comment]
I've experienced a similar issue. Found it was due to some global styled-jsx in my code. Check if you have anything modifying box-sizing globally. 

Regardless hopefully this is solved as theme changes shouldn't create UI changes unless the code in the theme contains gap changes etc

**Comment by Milo123459** [comment]
I don't have any custom css, except for something to give a underline on a link on hover. My theme shouldn't change anything in the UI. Very odd.

**Comment by Milo123459** [comment]
Any updates? @unix

**Comment by philmirez** [comment]
@Milo123459 try not using the `use-dark-mode` dependency. I would do exactly what the docs are doing. 
https://react.geist-ui.dev/en-us/guide/themes

**Comment by Milo123459** [comment]
How does the docs do it?

**Comment by Milo123459** [comment]
@unix any chance you could look into this..?

**Comment by moatorres** [comment]
@Milo123459 

I guess what @philmirez is saying is that instead of using a third-party dependency to toggle the themes you should use the example below to toggle themes, on your `pages/_app.tsx` file:

```tsx
  const [themeType, setThemeType] = useState('light')
  const switchThemes = () => {
    setThemeType(last => (last === 'dark' ? 'light' : 'dark'))
  }
```

Instead of importing `use-dark-mode`:

https://github.com/Milo123459/website/blob/aa360384782438f4c952ce08443cb65a72d53958/src/pages/_app.tsx#L16

Then you could use `switchThemes` on your `Select` components' `onChange` prop.

```tsx
<Select
							initialValue={themeType}
							onChange={(value) => {
								if (value == 'light') darkMode.enable();
								else darkMode.disable();
								// This fixes a bug where you could click the light mode button, if you were on light mode and it'd change to darkmode, then if you clicked darkmode whilst on darkmode it'd change to light
							}}
						>
```

Out of curiosity:  is there any specific reason for you to use this identation style?

**Comment by moatorres** [comment]
> I don't have any custom css, except for something to give a underline on a link on hover. My theme shouldn't change anything in the UI. Very odd.

I don't think you'd need that, then?

https://github.com/Milo123459/website/blob/aa360384782438f4c952ce08443cb65a72d53958/src/pages/_app.tsx#L10

**Comment by Milo123459** [comment]
I've since moved away from Geist, but thanks for the solution
