### ISSUE TITLE
Selecting item on Autocomplete when tapping mousepad sometimes dosen't trigger onSelect

### ISSUE THREAD

**Issue by matannahmani** [geist-org/react#592]
# Bug report 🐞

## Version & Environment

  - Chrome 92 on Linux
  - Geist v 2.1.4

## Expected Behaviour

When filling information on autocomplete and clicking on the drop-down result with laptop mousepad or tapping should trigger onSelect and fill results

## Actual results (or Errors)
Closes dropdown and trigger onSelect neither fill result

**Comment by memeree** [comment]
> 
> # Bug report 🐞
> ## Version & Environment
> 
>     * Chrome 92 on Linux
* Firefox 90.0.2 on Windows 10
> 
>     * Geist v 2.1.4
* Geist v2.1.5
> 
> 
> ## Expected Behaviour
> 
> When filling information on autocomplete and clicking on the drop-down result with laptop mousepad or tapping should trigger onSelect and fill results
When using "autocomplete" module, tapping a selection on the dropdown with mouse tap (not mouse click), the selection is not made, however using "select" module behaviour is that the selection is made. 
> ## Actual results (or Errors)
> 
> Closes dropdown and trigger onSelect neither fill result

**Comment by unix** [comment]
Although I still don't quite understand your issue, the `master` branch has been updated and both components have been improved, try it on [this link](https://react.geist-ui.dev/en-us/components/auto-complete) and see if it improves your issue.

**Comment by matannahmani** [comment]
Can confirm it's fixed Thanks again for you great work!
