### ISSUE TITLE
No Size Prop for components

### ISSUE THREAD

**Issue by JulianBuse** [geist-org/react#593]
# Bug report 🐞

There is no size prop for components. I use typescript, and found that there is an error when trying to set size. I looked at the definition, and found that it doesnt exist in the type declaration.

## Version & Environment

  - Firefox 90.0.2
  - Geist Ui version 2.2.0

## Expected Behaviour

The behavior I expect is that there is the ability to set size

## Actual results (or Errors)

I got an error:

```
interface Props {
    type?: ButtonTypes;
    ghost?: boolean;
    loading?: boolean;
    shadow?: boolean;
    auto?: boolean;
    effect?: boolean;
    disabled?: boolean;
    htmlType?: React.ButtonHTMLAttributes<any>['type'];
    icon?: React.ReactNode;
    iconRight?: React.ReactNode;
    onClick?: React.MouseEventHandler<HTMLButtonElement>;
    className?: string;
}
```

As you can see, no size prop. This is for the Button, but this issue exists for all components that should accept a size prop.

**Comment by ofekashery** [comment]
Please see #586.
