### ISSUE TITLE
Secondary theme override not changing secondary button colour

### ISSUE THREAD

**Issue by pierrenel** [geist-org/react#609]
# Bug report 🐞

## Version & Environment

  - Version of browser - Chrome 92
  - Version of `geist-ui/react` - 2.2.0

## Expected Behaviour

Have the ability to set the secondary background colour on a button

## Actual results (or Errors)

Setting the secondary colour in a custom theme, doesn't change the colour on a button where type = "secondary", it remains black/white.

```

const customTheme = Themes.createFromLight({
  type: 'custom',
  palette: {
    "background": "#ffffff",
    "foreground": "#020202",
    "selection": "#aedeff",
    "secondary": "#184892",
    "success": "#184892",
    "cyan": "#37d9d4",
    "violet": "#7c3aed",
    "purple": "#8b5cf6",
    "alert": "#ff5172",
    "link": "#3666b0"
  },
})
```

**Comment by unix** [comment]
same as #535
