### ISSUE TITLE
autocomplete on the Docs site does not auto complete on key presses

### ISSUE THREAD

**Issue by orenmizr** [geist-org/react#610]
# About `docs`

This is a document site related issue.

### Languages

  - [x] English

### Description
as is: autocomplete on the Docs site does not auto complete on key presses. 

i've tried it months ago and retested today... that is the first component i test in a react ui library - and this one does not seem to function as an autocomplete. 

it could be intended. but it does not see correct.

### Page Links 
https://react.geist-ui.dev/en-us/components/auto-complete

1. just type l o 
2. the list should narrow down to london
3. tab needs to choose the item.

**Comment by unix** [comment]
AutoComplete component does not support shortcuts.

**Comment by orenmizr** [comment]
what is a shortcuts you speak of... you just type a word... and it should complete and narrow like any autocomplete component. it  does not. if that is **by design** - fine. but it does not auto complete.
