### ISSUE TITLE
Uncaught TypeError: style.dynamic is not a function

### ISSUE THREAD

**Issue by jorgenbuilder** [geist-org/react#636]
# Bug report 🐞

Running a production build of this lib in vite results in the following error when attempting to render the page:

```
Uncaught TypeError: style.dynamic is not a function
```

The error seems to bubble up from several components in this library. I've seen it from Page and from CssBaseline.

## Version & Environment

  - Version of browser: chrome latest
  - Version of `geist-ui/react`: 2.2.0

## Expected Behaviour

The behavior I expect is for the page to render.

## Actual results (or Errors)

I got an error:

```
Uncaught TypeError: style.dynamic is not a function
```

**Comment by unix** [comment]
This issue has been fixed in v2.2.1: `yarn add @geist-ui/react@2.2.1`.

----
After clearing the cache, build and try, and if you still have issues, run `yarn why styled-jsx` to check if `styled-jsx` is installed, if not, please install this dependency manually: `yarn add styled-jsx -D`.
