### ISSUE TITLE
Could not resolve "@babel/runtime/helpers/esm/extends"

### ISSUE THREAD

**Issue by fengzilong** [geist-org/react#642]
# Bug report 🐞

## Version & Environment

  - Version of browser: latest chrome
  - Version of `geist-ui/react`: latest

## Expected Behaviour

The behavior I expect is no error reported

## Actual results (or Errors)

I got an error:

![image](https://user-images.githubusercontent.com/9125255/137582821-82950121-38a5-449e-9c1d-2c71ed30be12.png)

**BTW I am using Vite**

Some components depend on `@babel/runtime`, but when I bundle component without `@babel/runtime` installed( for example when I compile with esbuild or swc )

It's not kind for new users

**Comment by fengzilong** [comment]
Install `@babel/runtime` can solve this problem

Maybe we shall add `@babel/runtime` in `peerDependencies` or don't use babel to bundle component

**Comment by unix** [comment]
The difficulty here is that only users who use the `esm module` need these, but `peerDependencies ` cannot distinguish between these, do you have any suggestions for this?

**Comment by fengzilong** [comment]
> The difficulty here is that only users who use the `esm module` need these, but `peerDependencies` cannot distinguish between these, do you have any suggestions for this?

The problem is caused by inconsistency of umd & esm output. So one possible solution would be enabling `@babel/plugin-transform-runtime` in `webpack.config.js` to make babel helpers both reference the module `@babel/runtime` in umd & esm output. After doing that, we just need to add `peerDependencies` in package.json. ( It's a breaking change for users who are using umd output )

But here I would suggest another solution: use rollup to generate both `esm` and `umd` output, it will simplify the build script and make the umd & esm output consistent

**Comment by unix** [comment]
The build script requires 3 modes of output, and it is indeed the best solution if the output is consistent.
The previous failure to use Rollup was due to a compilation error in `styled-jsx`, and now that has fixed this issue, we should indeed upgrade the bundle script for better output.(rollup or esbuild)

Debugging and creating bundle scripts is a lot of work, are you interested in participating in this work?

**Comment by unix** [comment]
As a short-term fix, I first added `@babel/run-time` to the dependency:

- Non-esm users, as they will not be referenced, will not increase the size of the package.
- esm users, their project will always need the package, then the total package size remains unchanged.

**Comment by XeryYue** [comment]
@unix  I think may nedd a "sideEffects" field to package.json for tree shaking?
