### ISSUE TITLE
Create calendar component

### ISSUE THREAD

**Issue by daviddossantos** [geist-org/react#654]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

Hello guys, it would be interesting create calendar component

https://user-images.githubusercontent.com/37313667/144488354-e9b5feca-e032-44d3-bb39-dae40bf10e02.mov

**Comment by jaimin001** [comment]
Hey @daviddossantos , I would like to work in this issue. However, I am not able to understand this issue properly, like what will be the difference between a normal calendar component and the one you want?
Can you please explain me.

**Comment by daviddossantos** [comment]
hello @jaimin001, this calendar it's a print screen of platform Vercel, I would like that very much as an geist component

**Comment by jaimin001** [comment]
hey @daviddossantos,
I worked on this issue and have made a component like this.

Is it alright or do I have to make some more changes?
Please let me know 

https://user-images.githubusercontent.com/82583076/145685291-6221fc49-9a1c-4f36-b9db-3f1ccf4d9c39.mp4

**Comment by daviddossantos** [comment]
hey @jaimin001, I liked very much this, it's amazing.

I would be that the design stays a little bit equal weel of the Vercel, with this approach:

https://user-images.githubusercontent.com/37313667/145870861-327df17e-13e2-49c8-a782-f6a549099331.mov

**Comment by daviddossantos** [comment]
put your PR here and let's work this

**Comment by daviddossantos** [comment]
Relax @jaimin001  :slightly_smiling_face:

**Comment by daviddossantos** [comment]
What do you think of create a component of the zero, using Geist Component?

**Comment by daviddossantos** [comment]
Create the basic structure do Calendar

![image](https://user-images.githubusercontent.com/37313667/146815413-acce0ab6-4ee9-439f-ab7f-bd4546cc3b57.png)

**Comment by daviddossantos** [comment]
The code stayed in this way:

```
import { Divider, Grid, Page, Text, useTheme } from "@geist-ui/react";
import {
  Calendar as IconCalendar,
  ChevronLeft,
  ChevronRight,
  XCircle,
} from "@geist-ui/react-icons";
import { addDays, format, startOfWeek } from "date-fns";
import type { NextPage } from "next";

const Calendar: NextPage = () => {
  const { palette } = useTheme();

  const firstWeek = startOfWeek(new Date());
  const weekDay = Array.from(Array(7)).map((e, item) =>
    format(addDays(firstWeek, item), "EEE")
  );

  return (
    <Page>
      <Page.Content>
        <div className="container">
          <Text font="12px" type="secondary">
            DATE RANGE
          </Text>
          <div className="row">
            <Text font="20px" b>
              12/08/2021
              <Text font="20px" type="secondary" b>
                {` – `}
              </Text>
              12/15/2021
            </Text>
            <XCircle size={18} color={palette.secondary} />
          </div>
          <Divider
            className="divider"
            style={{
              margin: "10px -12px",
              maxWidth: 300,
            }}
          />
          <div className="row">
            <Text font="12px" className="text-month">
              DECEMBER 2021
            </Text>
            <div className="row">
              <Grid.Container gap={1.5} justify="center">
                <Grid>
                  <ChevronLeft size={20} color={palette.secondary} />
                </Grid>
                <Grid>
                  <IconCalendar size={18} color={palette.secondary} />
                </Grid>
                <Grid>
                  <ChevronRight size={20} color={palette.secondary} />
                </Grid>
              </Grid.Container>
            </div>
          </div>
          <Divider className="divider" />
          {weekDay.map((day) => (
            <th key={day} className="week-day">
              <Text type="secondary" font="12px">
                {day}
              </Text>
            </th>
          ))}
        </div>
        <style jsx>{`
          .container {
            width: 300px;
            height: 400px;
            padding: 12px;
            background: #fffc;
            box-shadow: 0 8px 30px rgba(0, 0, 0, 0.12);
            border-radius: 5px;
          }
          .row {
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            align-items: center;
          }
          .week-day {
            padding: 0 8px;
            font-weight: 500 !important;
            text-transform: uppercase;
          }
        `}</style>
      </Page.Content>
    </Page>
  );
};

export default Calendar;

```

**Comment by daviddossantos** [comment]
@ofekashery what do you think?

**Comment by unix** [comment]
The current task of geist is to maintain the current component, and no additional components will be added.
Thank you for your contribution @daviddossantos , but I have very little time to maintain the open source project in the last few months, so I will only merge the bug fixes.
