### ISSUE TITLE
Latest preact update causes Tabs components to be out of order

### ISSUE THREAD

**Issue by beans42** [geist-org/react#662]
# Bug report 🐞

Not sure if this is an issue with preact or geist, but the latest preact releases seem to have broken the `Tabs` component.

## Version & Environment

  - Version of preact: anything past 10.6.2
  - Version of `geist-ui/react`: latest

## Expected Behaviour

Tabs.Items elements to be listed in the order defined in JSX.

## Actual results (or Errors)

Tabs.Items are in reverse (?) order.

[Minimal working example](https://gist.github.com/beans42/dfc9c1a04edefdded8b4d98c9dd65962)

How it looks with preact 10.6.2:
![image](https://user-images.githubusercontent.com/53321702/148663790-b1381d50-48ff-4ffb-94fc-486b72e22f31.png)
How it looks with preact 10.6.3 and 10.6.4:
![image](https://user-images.githubusercontent.com/53321702/148663798-7de7ddba-7023-44d7-a0b6-443ad42ff9af.png)

[The offending preact update](https://github.com/preactjs/preact/compare/10.6.2...10.6.3#diff-c580d3b3982d2cf5341923532890e75fceb15c1fd1e7993f9b7ba897e3dbe2e1L291)
[The offending geist code](https://github.com/geist-org/react/blob/83ed1686513e1e6ed0f7fd29223cc546b5306d6c/components/tabs/tabs-item.tsx#L112) (I think?)

**Comment by Lzumikonata** [comment]
[CodeSandbox](https://codesandbox.io/s/misty-fast-nckr8?file=/src/components/child.tsx)
In the local test of Preact(version: 10.6.2, 10.6.3), The initialization order of child components is incorrect, which seems to be a problem of Preact. Please see the `Label` printing order of Child in this example.

**Comment by unix** [comment]
Thanks @Lzumikonata, I also verified that this is indeed a preact lifecycle issue.

**Comment by jaredkrinke** [comment]
Is there a Preact bug tracking the issue you noted?
