### ISSUE TITLE
Compatibility with tailwind?

### ISSUE THREAD

**Issue by 10000multiplier** [geist-org/react#664]
# Bug report 🐞

Sadly geist doesn't seem compatible with tailwind, i.e. doing something like this does not work:

```jsx
import { Page } from "@geist-ui/react";

<Page className="bg-red">
```

## Version & Environment

  - Version of `geist-ui/react`: v2.2.0

## Expected Behaviour

The behavior I expect is it just works.

## Actual results (or Errors)

nothing happens

**Comment by unix** [comment]
- refs: #317 #240
- Under the current design, geist is not affected by the class names of the default weights.

**Comment by 10000multiplier** [comment]
ah, thanks
