### ISSUE TITLE
The 2.2.0 release has broken TypeScript typings

### ISSUE THREAD

**Issue by julienvincent** [geist-org/react#673]
# Bug report 🐞

## Version & Environment

  - Version of browser - N/A
  - Version of `geist-ui/react` - v2.2.2

## Expected Behaviour

The expected behaviour while using geist-ui in a TypeScript project would be to have detailed typings for all exported components. This seems to be a regression from `2.1.5` whose types continue to work as expected.

## Actual results (or Errors)

All exported components are typed as `any`: 

![image](https://user-images.githubusercontent.com/8571121/149799946-0f49e96c-87b9-4a80-9bed-83b583e6a776.png)

Including nested components:

![image](https://user-images.githubusercontent.com/8571121/149800044-d1215792-52a6-447d-89a7-fc6564acc7ca.png)

## Workarounds

A really hacky and temporary workaround was to install an aliased version of `@geist-ui/react@2.1.5` and re-declare the type exports.

```ts
// package.json

{
  "dependencies": {
    "@geist-ui/react": "^2.2.2",
    "geist-types": "npm:@geist-ui/react@2.1.5",
  }
}
```

```ts
// geist.d.ts

declare module '@geist-ui/react' {
  export * from 'geist-types';
}
```

This obviously results in some type mismatches, for example while using the `Spacer` component which had a breaking change. For this case I am using `@ts-ignore` statements.

```tsx
...
  {/* @ts-ignore */}
  <G.Spacer w={1}></G.Spacer>
...
```

**Comment by unix** [comment]
I have release a development version to fix the type error, you can use it for development fist: `yarn add @geist-ui/react@2.2.3-dev.0`, and a patch version will be released later.

**Comment by unix** [comment]
Version `2.2.3` has been released(`yarn add @geist-ui/react@latest`) and tests show that this type of bug has been fixed.

For any follow-up on this issue, please reopen this issue.

**Comment by julienvincent** [comment]
Works! Thanks 🎉
